/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './cd-timer';
const styles_CdTimerComponent:any[] = ([] as any[]);
export const RenderType_CdTimerComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_CdTimerComponent,data:{}});
export function View_CdTimerComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),[' '])),i0.ɵncd((null as any),0)],
      (null as any),(null as any));
}
export function View_CdTimerComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'cd-timer',([] as any[]),
      (null as any),(null as any),(null as any),View_CdTimerComponent_0,RenderType_CdTimerComponent)),
      i0.ɵdid(4374528,(null as any),0,i1.CdTimerComponent,[i0.ElementRef,i0.Renderer2],
          (null as any),(null as any))],(null as any),(null as any));
}
export const CdTimerComponentNgFactory:i0.ComponentFactory<i1.CdTimerComponent> = i0.ɵccf('cd-timer',
    i1.CdTimerComponent,View_CdTimerComponent_Host_0,{startTime:'startTime',endTime:'endTime',
        countdown:'countdown',autoStart:'autoStart',maxTimeUnit:'maxTimeUnit',format:'format'},
    {onStart:'onStart',onStop:'onStop',onTick:'onTick',onComplete:'onComplete'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiZDovcHJvamVjdHMvMDJfd2ViX2Zyb250ZW5kL0dpdGh1Yi9jZC10aW1lci9saWIvY2QtdGltZXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vZDovcHJvamVjdHMvMDJfd2ViX2Zyb250ZW5kL0dpdGh1Yi9jZC10aW1lci9saWIvY2QtdGltZXIudHMiLCJuZzovLy9kOi9wcm9qZWN0cy8wMl93ZWJfZnJvbnRlbmQvR2l0aHViL2NkLXRpbWVyL2xpYi9jZC10aW1lci50cy5DZFRpbWVyQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9kOi9wcm9qZWN0cy8wMl93ZWJfZnJvbnRlbmQvR2l0aHViL2NkLXRpbWVyL2xpYi9jZC10aW1lci50cy5DZFRpbWVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiIDxuZy1jb250ZW50PjwvbmctY29udGVudD4iLCI8Y2QtdGltZXI+PC9jZC10aW1lcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQSw2Q0FBQzs7OztvQkNBRDtNQUFBO2FBQUE7VUFBQTs7Ozs7In0=
